#!/bin/sh

# Editng a file with emacs 23+ in unibyte mode.

# 2021 (c) Hin-Tak Leung 


# Reference:
#     https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Disabling-Multibyte
#
# There are three ways to edit a particular file in unibyte representation:
#
#   - Visit it using "find-file-literally"
#       Also mentioned in https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#Text-Coding
#
#   - Using "raw-text" as the coding system
#
#   - Invoking the command "toggle-enable-multibyte-characters" in that buffer
#
# Before emacs 23, there was an "--unibyte" option. 

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 EXISTING-FILENAME"
  exit 1
fi

emacs -Q -nw --eval "(progn (setq unibyte-display-via-language-environment t) (find-file-literally \"${1}\"))"

